import { Component } from '@angular/core';




interface productDetails {
  name: string;
  color: string;
  weight: number;
  prise: number;
  issolded: boolean;
  discount?: number;
  isStock: number;
  pImage: string;
}

@Component({
  selector: 'app-product-list',
  templateUrl: './product-list.component.html',
  styleUrls: ['./product-list.component.css']
})


export class ProductListComponent {

  
  products = [
    {
      id: 1,
      name: "Nike React Infinity Run Flyknit",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "NIKE",
      gender: "MEN",
      category: "RUNNING",
      size: [6, 7, 8, 9, 10],
      color: ["White", "Blue", "Black"],
      price: 160,
      is_in_inventory: true,
      discount: 30,
      items_left: 3,
      imageURL: "https://picsum.photos/id/1/600/400",
      slug: "nike-react-infinity-run-flyknit"
    },
    {
      id: 2,
      name: "Nike Air Force 1 '07",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "NIKE",
      gender: "MEN",
      category: "LIFESTYLE",
      size: [7, 8, 9, 10, 11],
      color: ["White", "Black"],
      price: 110,
      is_in_inventory: false,
      items_left: 15,

      imageURL: "https://picsum.photos/id/2/600/400",
      slug: "nike-air-force-1-07"
    },
    {
      id: 3,
      name: "Adidas Ultraboost Light",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "ADIDAS",
      gender: "MEN",
      category: "RUNNING",
      size: [8, 9, 10, 11, 12],
      color: ["Black", "White"],
      price: 190,
      is_in_inventory: true,
      items_left: 7, discount: 60,
      imageURL: "https://picsum.photos/id/3/600/400",
      slug: "adidas-ultraboost-light"
    },
    {
      id: 4,
      name: "Adidas Stan Smith",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "ADIDAS",
      gender: "WOMEN",
      category: "CASUAL",
      size: [5, 6, 7, 8, 9],
      color: ["White", "Green"],
      price: 100,
      is_in_inventory: false,
      items_left: 12,
      imageURL: "https://picsum.photos/id/4/600/400",
      slug: "adidas-stan-smith"
    },
    {
      id: 5,
      name: "Puma RS-X Efekt",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "PUMA",
      gender: "MEN",
      category: "LIFESTYLE", discount: 80,
      size: [7, 8, 9, 10, 11],
      color: ["Black", "White", "Blue"],
      price: 120,
      is_in_inventory: true,
      items_left: 8,
      imageURL: "https://picsum.photos/id/5/600/400",
      slug: "puma-rs-x-efekt"
    },
    {
      id: 6,
      name: "New Balance 574 Core",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "NEW BALANCE",
      gender: "UNISEX",
      category: "CASUAL",
      size: [6, 7, 8, 9, 10, 11, 12],
      color: ["Gray", "Navy"],
      price: 90, discount: 10,

      is_in_inventory: true,
      items_left: 20,
      imageURL: "https://picsum.photos/id/6/600/400",
      slug: "new-balance-574-core"
    },
    {
      id: 7,
      name: "Converse Chuck Taylor All Star",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "CONVERSE",
      gender: "UNISEX",
      category: "CASUAL",
      size: [6, 7, 8, 9, 10, 11],
      color: ["Black", "White"],
      price: 65, discount: 10,

      is_in_inventory: false,
      items_left: 25,
      imageURL: "https://picsum.photos/id/7/600/400",
      slug: "converse-chuck-taylor"
    },
    {
      id: 8,
      name: "Nike Air Max 270",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "NIKE",
      gender: "WOMEN",
      category: "LIFESTYLE",
      size: [5, 6, 7, 8, 9],
      color: ["White", "Pink"],
      discount: 40,

      price: 160,
      is_in_inventory: false,
      items_left: 6,
      imageURL: "https://picsum.photos/id/8/600/400",
      slug: "nike-air-max-270"
    },
    {
      id: 9,
      name: "Adidas NMD_R1",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "ADIDAS",
      gender: "MEN",
      category: "LIFESTYLE",
      size: [8, 9, 10, 11, 12],
      color: ["Black", "White"],
      price: 150,
      is_in_inventory: false,
      items_left: 4,
      imageURL: "https://picsum.photos/id/9/600/400",
      slug: "adidas-nmd-r1"
    },
    {
      id: 10,
      name: "Puma Cali Dream",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "PUMA",
      gender: "WOMEN",
      category: "LIFESTYLE",
      size: [5, 6, 7, 8, 9],
      color: ["White", "Pink"], discount: 30,
      price: 100,
      is_in_inventory: true,
      items_left: 10,
      imageURL: "https://picsum.photos/id/10/600/400",
      slug: "puma-cali-dream"
    },
    {
      id: 11,
      name: "Nike Jordan 1 Mid",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "NIKE",
      gender: "MEN",
      category: "BASKETBALL",
      size: [8, 9, 10, 11, 12],
      color: ["Black", "Red"], discount: 30,
      price: 125,
      is_in_inventory: true,
      items_left: 3,
      imageURL: "https://picsum.photos/id/11/600/400",
      slug: "nike-jordan-1-mid"
    },
    {
      id: 12,
      name: "Vans Old Skool",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "VANS",
      gender: "UNISEX",
      category: "SKATEBOARDING",
      size: [6, 7, 8, 9, 10, 11],
      color: ["Black", "White"],
      price: 70,
      is_in_inventory: true,
      items_left: 18,
      imageURL: "https://picsum.photos/id/12/600/400",
      slug: "vans-old-skool"
    },
    {
      id: 13,
      name: "Reebok Classic Leather",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "REEBOK",
      gender: "MEN",
      category: "CASUAL",
      size: [8, 9, 10, 11, 12],
      color: ["White", "Black"],
      price: 85,
      is_in_inventory: true,
      items_left: 14,
      imageURL: "https://picsum.photos/id/13/600/400",
      slug: "reebok-classic-leather"
    },
    {
      id: 14,
      name: "Nike Metcon 8",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "NIKE",
      gender: "MEN", discount: 30,
      category: "TRAINING",
      size: [8, 9, 10, 11, 12],
      color: ["Black", "Blue"],
      price: 130,
      is_in_inventory: true,
      items_left: 9,
      imageURL: "https://picsum.photos/id/14/600/400",
      slug: "nike-metcon-8"
    },
    {
      id: 15,
      name: "Adidas Superstar",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "ADIDAS",
      gender: "UNISEX",
      category: "CASUAL",
      size: [6, 7, 8, 9, 10, 11, 12],
      color: ["White", "Black"],
      price: 100,
      is_in_inventory: true, discount: 30,
      items_left: 22,
      imageURL: "https://picsum.photos/id/15/600/400",
      slug: "adidas-superstar"
    },
    {
      id: 16,
      name: "Puma Future Rider",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "PUMA",
      gender: "MEN",
      category: "LIFESTYLE",
      size: [7, 8, 9, 10, 11],
      color: ["Blue", "White"],
      price: 90,
      is_in_inventory: true,
      items_left: 11,
      imageURL: "https://picsum.photos/id/16/600/400",
      slug: "puma-future-rider"
    },
    {
      id: 17,
      name: "New Balance 990v6",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "NEW BALANCE",
      gender: "MEN",
      category: "RUNNING",
      size: [8, 9, 10, 11, 12], discount: 30,
      color: ["Gray", "Black"],
      price: 195,
      is_in_inventory: true,
      items_left: 5,
      imageURL: "https://picsum.photos/id/17/600/400",
      slug: "new-balance-990v6"
    },
    {
      id: 18,
      name: "Nike Blazer Mid '77",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "NIKE",
      gender: "WOMEN",
      category: "LIFESTYLE",
      size: [5, 6, 7, 8, 9],
      color: ["White", "Black"],
      price: 110,
      is_in_inventory: true,
      items_left: 8,
      imageURL: "https://picsum.photos/id/18/600/400",
      slug: "nike-blazer-mid-77"
    },
    {
      id: 19,
      name: "Adidas Gazelle",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "ADIDAS",
      gender: "UNISEX",
      category: "LIFESTYLE",
      size: [6, 7, 8, 9, 10, 11],
      color: ["Blue", "Black"], discount: 30,
      price: 100,
      is_in_inventory: true,
      items_left: 16,
      imageURL: "https://picsum.photos/id/19/600/400",
      slug: "adidas-gazelle"
    },
    {
      id: 20,
      name: "Asics Gel-Kayano 29",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "ASICS",
      gender: "MEN",
      category: "RUNNING",
      size: [8, 9, 10, 11, 12],
      color: ["Blue", "Black"],
      price: 160,
      is_in_inventory: true,
      items_left: 6, discount: 30,
      imageURL: "https://picsum.photos/id/20/600/400",
      slug: "asics-gel-kayano-29"
    },
    {
      id: 21,
      name: "Saucony Jazz Original",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "SAUCONY",
      gender: "UNISEX",
      category: "CASUAL",
      size: [7, 8, 9, 10, 11], discount: 30,
      color: ["White", "Blue"],
      price: 80,
      is_in_inventory: true,
      items_left: 13,
      imageURL: "https://picsum.photos/id/21/600/400",
      slug: "saucony-jazz-original"
    },
    {
      id: 22,
      name: "Under Armour HOVR Machina 3",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "UNDER ARMOUR",
      gender: "MEN",
      category: "RUNNING",
      size: [8, 9, 10, 11, 12],
      color: ["Black", "Red"],
      price: 150,
      is_in_inventory: true, discount: 30,
      items_left: 7,
      imageURL: "https://picsum.photos/id/22/600/400",
      slug: "under-armour-hovr-machina-3"
    },
    {
      id: 23,
      name: "Nike Dunk Low Retro",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "NIKE",
      gender: "UNISEX", discount: 30,
      category: "SKATEBOARDING",
      size: [6, 7, 8, 9, 10, 11, 12],
      color: ["Black", "White"],
      price: 110,
      is_in_inventory: true,
      items_left: 4,
      imageURL: "https://picsum.photos/id/23/600/400",
      slug: "nike-dunk-low-retro"
    },
    {
      id: 24,
      name: "Adidas Forum Low",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "ADIDAS",
      gender: "WOMEN",
      category: "BASKETBALL", discount: 30,
      size: [5, 6, 7, 8, 9],
      color: ["White", "Purple"],
      price: 120,
      is_in_inventory: true,
      items_left: 9,
      imageURL: "https://picsum.photos/id/24/600/400",
      slug: "adidas-forum-low"
    }
  ];
  totalProductscount = this.products.length
  totalProductsinStockcount= this.products.filter( (p)=> p.is_in_inventory===true).length
  totalProductsoutStockcount= this.products.filter( (p)=> p.is_in_inventory !== true).length

    selectedFilterRadioButton :string = 'all'
    
    onFilterChanged(value : string){
      this.selectedFilterRadioButton= value;
    }
  products1 = [
    {
      id: 1,
      name: "Nike React Infinity Run Flyknit",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "NIKE",
      gender: "MEN",
      category: "RUNNING",
      size: [6, 7, 8, 9, 10],
      color: ["White", "Blue", "Black"],
      price: 160,
      is_in_inventory: true,
      items_left: 3,
      imageURL: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/i1-665455a5-45de-40fb-945f-c1852b82400d/react-infinity-run-flyknit-mens-running-shoe-zXgqVq.jpg",
      slug: "nike-react-infinity-run-flyknit"
    },
    {
      id: 2,
      name: "Nike Air Force 1 '07",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "NIKE",
      gender: "MEN",
      category: "LIFESTYLE",
      size: [7, 8, 9, 10, 11],
      color: ["White", "Black"],
      price: 110,
      is_in_inventory: true,
      items_left: 15,
      imageURL: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/e6da41fa-1be4-4ce5-b89c-22be4f1f02d4/air-force-1-07-mens-shoe-5WGZWg.png",
      slug: "nike-air-force-1-07"
    },
    {
      id: 3,
      name: "Adidas Ultraboost Light",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "ADIDAS",
      gender: "MEN",
      category: "RUNNING",
      size: [8, 9, 10, 11, 12],
      color: ["Black", "White"],
      price: 190,
      is_in_inventory: true,
      items_left: 7,
      imageURL: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/96b8a4f871d246c1b390af8a00fb6fe4_9366/Ultraboost_Light_Shoes_Black_HP9201_01_standard.jpg",
      slug: "adidas-ultraboost-light"
    },
    {
      id: 4,
      name: "Adidas Stan Smith",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "ADIDAS",
      gender: "WOMEN",
      category: "CASUAL",
      size: [5, 6, 7, 8, 9],
      color: ["White", "Green"],
      price: 100,
      is_in_inventory: true,
      items_left: 12,
      imageURL: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/2f804a4c7d8f4158b3f3af8e00fb6c4f_9366/Stan_Smith_Shoes_White_M20324_01_standard.jpg",
      slug: "adidas-stan-smith"
    },
    {
      id: 5,
      name: "Puma RS-X Efekt",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "PUMA",
      gender: "MEN",
      category: "LIFESTYLE",
      size: [7, 8, 9, 10, 11],
      color: ["Black", "White", "Blue"],
      price: 120,
      is_in_inventory: true,
      items_left: 8,
      imageURL: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:f8f8f8,w_600,h_600/global/306129/01/sv01/fnd/EEA/fmt/png/RS-X-Efekt-Men's-Sneakers",
      slug: "puma-rs-x-efekt"
    },
    {
      id: 6,
      name: "New Balance 574 Core",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "NEW BALANCE",
      gender: "UNISEX",
      category: "CASUAL",
      size: [6, 7, 8, 9, 10, 11, 12],
      color: ["Gray", "Navy"],
      price: 90,
      is_in_inventory: true,
      items_left: 20,
      imageURL: "https://nb.scene7.com/is/image/NB/m574gn1_nb_02_i?$dw_detail_main_lg$&bgc=f1f1f1&layer=1&bgcolor=f1f1f1&blendMode=mult&scale=10&wid=1600&hei=1600",
      slug: "new-balance-574-core"
    },
    {
      id: 7,
      name: "Converse Chuck Taylor All Star",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "CONVERSE",
      gender: "UNISEX",
      category: "CASUAL",
      size: [6, 7, 8, 9, 10, 11],
      color: ["Black", "White"],
      price: 65,
      is_in_inventory: true,
      items_left: 25,
      imageURL: "https://images.converse.com/dw/image/v2/BCZC_PRD/on/demandware.static/-/Sites-converse-master/default/dw3d91b1b2/images/107355C_107355C_1.jpg",
      slug: "converse-chuck-taylor"
    },
    {
      id: 8,
      name: "Nike Air Max 270",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "NIKE",
      gender: "WOMEN",
      category: "LIFESTYLE",
      size: [5, 6, 7, 8, 9],
      color: ["White", "Pink"],
      price: 160,
      is_in_inventory: true,
      items_left: 6,
      imageURL: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/i1-5c4d0b0f-8b6c-4c9e-9b0a-3b3b3b3b3b3b/air-max-270-womens-shoe-Pz6qZQ.png",
      slug: "nike-air-max-270"
    },
    {
      id: 9,
      name: "Adidas NMD_R1",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "ADIDAS",
      gender: "MEN",
      category: "LIFESTYLE",
      size: [8, 9, 10, 11, 12],
      color: ["Black", "White"],
      price: 150,
      is_in_inventory: true,
      items_left: 4,
      imageURL: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b_9366/NMD_R1_Shoes_Black_FY6862_01_standard.jpg",
      slug: "adidas-nmd-r1"
    },
    {
      id: 10,
      name: "Puma Cali Dream",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "PUMA",
      gender: "WOMEN",
      category: "LIFESTYLE",
      size: [5, 6, 7, 8, 9],
      color: ["White", "Pink"],
      price: 100,
      is_in_inventory: true,
      items_left: 10,
      imageURL: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:f8f8f8,w_600,h_600/global/372422/01/sv01/fnd/EEA/fmt/png/Cali-Dream-Women's-Sneakers",
      slug: "puma-cali-dream"
    },
    {
      id: 11,
      name: "Nike Jordan 1 Mid",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "NIKE",
      gender: "MEN",
      category: "BASKETBALL",
      size: [8, 9, 10, 11, 12],
      color: ["Black", "Red"],
      price: 125,
      is_in_inventory: true,
      items_left: 3,
      imageURL: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/i1-8b8b8b8b8b8b8b8b8b8b8b8b8b8b8b8b/air-jordan-1-mid-shoe-4h0h0h.png",
      slug: "nike-jordan-1-mid"
    },
    {
      id: 12,
      name: "Vans Old Skool",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "VANS",
      gender: "UNISEX",
      category: "SKATEBOARDING",
      size: [6, 7, 8, 9, 10, 11],
      color: ["Black", "White"],
      price: 70,
      is_in_inventory: true,
      items_left: 18,
      imageURL: "https://images.vans.com/is/image/Vans/VN000D3HY28-HERO?$VFDP-VIEWER-ZOOMVIEW-HERO$",
      slug: "vans-old-skool"
    },
    {
      id: 13,
      name: "Reebok Classic Leather",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "REEBOK",
      gender: "MEN",
      category: "CASUAL",
      size: [8, 9, 10, 11, 12],
      color: ["White", "Black"],
      price: 85,
      is_in_inventory: true,
      items_left: 14,
      imageURL: "https://reebok.centracdn.net/client/dynamic/images/214_214c8c8c8c8c8c8c8c8c8c8c8c8c8c8c8c.jpg",
      slug: "reebok-classic-leather"
    },
    {
      id: 14,
      name: "Nike Metcon 8",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "NIKE",
      gender: "MEN",
      category: "TRAINING",
      size: [8, 9, 10, 11, 12],
      color: ["Black", "Blue"],
      price: 130,
      is_in_inventory: true,
      items_left: 9,
      imageURL: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/i1-9d9d9d9d9d9d9d9d9d9d9d9d9d9d9d9d/metcon-8-mens-training-shoe-zXgqVq.png",
      slug: "nike-metcon-8"
    },
    {
      id: 15,
      name: "Adidas Superstar",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "ADIDAS",
      gender: "UNISEX",
      category: "CASUAL",
      size: [6, 7, 8, 9, 10, 11, 12],
      color: ["White", "Black"],
      price: 100,
      is_in_inventory: true,
      items_left: 22,
      imageURL: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b_9366/Superstar_Shoes_White_EG4958_01_standard.jpg",
      slug: "adidas-superstar"
    },
    {
      id: 16,
      name: "Puma Future Rider",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "PUMA",
      gender: "MEN",
      category: "LIFESTYLE",
      size: [7, 8, 9, 10, 11],
      color: ["Blue", "White"],
      price: 90,
      is_in_inventory: true,
      items_left: 11,
      imageURL: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:f8f8f8,w_600,h_600/global/369847/01/sv01/fnd/EEA/fmt/png/Future-Rider-Men's-Sneakers",
      slug: "puma-future-rider"
    },
    {
      id: 17,
      name: "New Balance 990v6",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "NEW BALANCE",
      gender: "MEN",
      category: "RUNNING",
      size: [8, 9, 10, 11, 12],
      color: ["Gray", "Black"],
      price: 195,
      is_in_inventory: true,
      items_left: 5,
      imageURL: "https://nb.scene7.com/is/image/NB/m990gl6_nb_02_i?$dw_detail_main_lg$&bgc=f1f1f1&layer=1&bgcolor=f1f1f1&blendMode=mult&scale=10&wid=1600&hei=1600",
      slug: "new-balance-990v6"
    },
    {
      id: 18,
      name: "Nike Blazer Mid '77",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "NIKE",
      gender: "WOMEN",
      category: "LIFESTYLE",
      size: [5, 6, 7, 8, 9],
      color: ["White", "Black"],
      price: 110,
      is_in_inventory: true,
      items_left: 8,
      imageURL: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/i1-7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c/blazer-mid-77-womens-shoe-NkQbQq.png",
      slug: "nike-blazer-mid-77"
    },
    {
      id: 19,
      name: "Adidas Gazelle",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "ADIDAS",
      gender: "UNISEX",
      category: "LIFESTYLE",
      size: [6, 7, 8, 9, 10, 11],
      color: ["Blue", "Black"],
      price: 100,
      is_in_inventory: true,
      items_left: 16,
      imageURL: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b_9366/Gazelle_Shoes_Blue_BZ0601_01_standard.jpg",
      slug: "adidas-gazelle"
    },
    {
      id: 20,
      name: "Asics Gel-Kayano 29",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "ASICS",
      gender: "MEN",
      category: "RUNNING",
      size: [8, 9, 10, 11, 12],
      color: ["Blue", "Black"],
      price: 160,
      is_in_inventory: true,
      items_left: 6,
      imageURL: "https://www.asics.com/dw/image/v2/BBXC_PRD/on/demandware.static/-/Sites-asics-us-Library/default/dw6b6b6b6b6/images/gel-kayano-29-men-running-shoes.jpg",
      slug: "asics-gel-kayano-29"
    },
    {
      id: 21,
      name: "Saucony Jazz Original",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "SAUCONY",
      gender: "UNISEX",
      category: "CASUAL",
      size: [7, 8, 9, 10, 11],
      color: ["White", "Blue"],
      price: 80,
      is_in_inventory: true,
      items_left: 13,
      imageURL: "https://www.saucony.com/dw/image/v2/BBXC_PRD/on/demandware.static/-/Sites-saucony-us-Library/default/dw7c7c7c7c7/images/jazz-original-unisex-sneakers.jpg",
      slug: "saucony-jazz-original"
    },
    {
      id: 22,
      name: "Under Armour HOVR Machina 3",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "UNDER ARMOUR",
      gender: "MEN",
      category: "RUNNING",
      size: [8, 9, 10, 11, 12],
      color: ["Black", "Red"],
      price: 150,
      is_in_inventory: true,
      items_left: 7,
      imageURL: "https://underarmour.scene7.com/is/image/UnderArmour/3025599-001_DEFAULT?$PDP_GALLERY$",
      slug: "under-armour-hovr-machina-3"
    },
    {
      id: 23,
      name: "Nike Dunk Low Retro",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "NIKE",
      gender: "UNISEX",
      category: "SKATEBOARDING",
      size: [6, 7, 8, 9, 10, 11, 12],
      color: ["Black", "White"],
      price: 110,
      is_in_inventory: true,
      items_left: 4,
      imageURL: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/i1-6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d6d/dunk-low-retro-mens-shoe-4h0h0h.png",
      slug: "nike-dunk-low-retro"
    },
    {
      id: 24,
      name: "Adidas Forum Low",
      description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
      brand: "ADIDAS",
      gender: "WOMEN",
      category: "BASKETBALL",
      size: [5, 6, 7, 8, 9],
      color: ["White", "Purple"],
      price: 120,
      is_in_inventory: true,
      items_left: 9,
      imageURL: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b_9366/Forum_Low_Shoes_White_FY7756_01_standard.jpg",
      slug: "adidas-forum-low"
    }
  ];


  productCategory: string = "Accesories";
  productNumber: number = 7834658234;

  product1Details: productDetails = {
    name: "laptop",
    color: "Red",
    weight: 0.5,
    prise: 999,
    issolded: false,
    discount: 14,
    isStock: 0,
    pImage: "~../../assets/photo-1678685888221-cda773a3dcdb.jpeg"

  }

  getdiscount() {
    return this.product1Details.prise - (this.product1Details.prise * this.product1Details.discount / 100)
  }


}
